// Mock data for TaskFlow application

export const currentUser = {
  id: 'user-1',
  name: 'Sarah Chen',
  email: 'sarah@taskflow.io',
  avatar: null,
  initials: 'SC',
  role: 'Admin',
};

export const initialWorkers = [
  {
    id: 'user-1',
    name: 'Sarah Chen',
    email: 'sarah@taskflow.io',
    avatar: null,
    initials: 'SC',
    role: 'Admin',
  },
  {
    id: 'user-2',
    name: 'Alexander Pierce',
    email: 'alex.p@taskflow.io',
    avatar: null,
    initials: 'AP',
    role: 'Admin',
  },
  {
    id: 'user-3',
    name: 'Sarah Connor',
    email: 's.connor@taskflow.io',
    avatar: null,
    initials: 'SC',
    role: 'Member',
  },
  {
    id: 'user-4',
    name: 'Marcus Wright',
    email: 'm.wright@taskflow.io',
    avatar: null,
    initials: 'MW',
    role: 'Member',
  },
  {
    id: 'user-5',
    name: 'Alex Rivera',
    email: 'a.rivera@taskflow.io',
    avatar: null,
    initials: 'AR',
    role: 'Member',
  },
];

export const initialProjects = [
  {
    id: 'proj-1',
    name: 'Website Redesign',
    description: 'Complete overhaul of the company website with modern design principles.',
    color: '#4F46E5',
    createdAt: '2026-04-10T10:00:00Z',
  },
  {
    id: 'proj-2',
    name: 'Mobile App v2',
    description: 'Second iteration of the mobile application with new features.',
    color: '#10B981',
    createdAt: '2026-04-12T09:00:00Z',
  },
  {
    id: 'proj-3',
    name: 'Core Infrastructure',
    description: 'Backend services and infrastructure improvements.',
    color: '#F59E0B',
    createdAt: '2026-04-15T14:00:00Z',
  },
];

export const initialTasks = [
  // Website Redesign tasks
  {
    id: 'task-1',
    title: 'Define information architecture and sitemap',
    description: 'Create a comprehensive sitemap and define the information architecture for the new website.',
    status: 'todo',
    priority: 'high',
    projectId: 'proj-1',
    assigneeId: 'user-1',
    dueDate: '2026-04-30',
    createdAt: '2026-04-10T10:00:00Z',
  },
  {
    id: 'task-2',
    title: 'Create responsive UI components for navigation',
    description: 'Build a responsive navigation system that works across all breakpoints.',
    status: 'todo',
    priority: 'medium',
    projectId: 'proj-1',
    assigneeId: 'user-2',
    dueDate: '2026-05-05',
    createdAt: '2026-04-11T09:00:00Z',
  },
  {
    id: 'task-3',
    title: 'Integrate Contentful CMS with Next.js frontend',
    description: 'Set up Contentful CMS integration for dynamic content management.',
    status: 'in-progress',
    priority: 'high',
    projectId: 'proj-1',
    assigneeId: 'user-3',
    dueDate: '2026-05-10',
    createdAt: '2026-04-12T11:00:00Z',
  },
  {
    id: 'task-4',
    title: 'Internal QA and bug tracking',
    description: 'Set up QA processes and bug tracking workflows.',
    status: 'in-progress',
    priority: 'low',
    projectId: 'proj-1',
    assigneeId: 'user-4',
    dueDate: '2026-05-15',
    createdAt: '2026-04-13T08:00:00Z',
  },
  {
    id: 'task-5',
    title: 'Initial project kickoff and stakeholder alignment',
    description: 'Align all stakeholders and define project goals.',
    status: 'done',
    priority: 'high',
    projectId: 'proj-1',
    assigneeId: 'user-1',
    dueDate: '2026-04-15',
    createdAt: '2026-04-10T10:00:00Z',
  },
  // Mobile App tasks
  {
    id: 'task-6',
    title: 'Design new onboarding flow',
    description: 'Create an intuitive onboarding experience for new users.',
    status: 'todo',
    priority: 'high',
    projectId: 'proj-2',
    assigneeId: 'user-5',
    dueDate: '2026-05-01',
    createdAt: '2026-04-12T09:00:00Z',
  },
  {
    id: 'task-7',
    title: 'Implement push notification system',
    description: 'Set up push notifications for real-time updates.',
    status: 'in-progress',
    priority: 'medium',
    projectId: 'proj-2',
    assigneeId: 'user-2',
    dueDate: '2026-05-08',
    createdAt: '2026-04-14T10:00:00Z',
  },
  {
    id: 'task-8',
    title: 'User authentication refactor',
    description: 'Refactor the authentication system for better security.',
    status: 'done',
    priority: 'high',
    projectId: 'proj-2',
    assigneeId: 'user-3',
    dueDate: '2026-04-20',
    createdAt: '2026-04-12T10:00:00Z',
  },
  // Core Infrastructure tasks
  {
    id: 'task-9',
    title: 'API Integration for Dashboard',
    description: 'Build REST API endpoints for the dashboard data.',
    status: 'todo',
    priority: 'high',
    projectId: 'proj-3',
    assigneeId: 'user-4',
    dueDate: '2026-05-03',
    createdAt: '2026-04-15T14:00:00Z',
  },
  {
    id: 'task-10',
    title: 'Database schema migration',
    description: 'Migrate database schemas to the new architecture.',
    status: 'done',
    priority: 'medium',
    projectId: 'proj-3',
    assigneeId: 'user-1',
    dueDate: '2026-04-22',
    createdAt: '2026-04-15T14:00:00Z',
  },
  {
    id: 'task-11',
    title: 'Set up CI/CD pipeline',
    description: 'Configure automated build and deployment pipelines.',
    status: 'in-progress',
    priority: 'medium',
    projectId: 'proj-3',
    assigneeId: 'user-5',
    dueDate: '2026-05-12',
    createdAt: '2026-04-16T09:00:00Z',
  },
];

export const initialActivities = [
  {
    id: 'act-1',
    userId: 'user-5',
    action: 'updated the Landing Page Design',
    projectName: 'Website Redesign',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-2',
    userId: 'user-1',
    action: 'completed Database Schema Migration',
    projectName: 'Core Infrastructure',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-3',
    userId: 'user-1',
    action: 'scheduled Team Meeting for tomorrow at 10:00 AM',
    projectName: null,
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-4',
    userId: 'user-4',
    action: 'joined the Frontend Project',
    projectName: 'Website Redesign',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-5',
    userId: 'user-2',
    action: 'created a new task: Design new onboarding flow',
    projectName: 'Mobile App v2',
    timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
];

export const projectColors = [
  '#4F46E5', '#10B981', '#F59E0B', '#EF4444',
  '#8B5CF6', '#EC4899', '#06B6D4', '#F97316',
  '#14B8A6', '#6366F1',
];
